image: gitpod/workspace-postgres

tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 5173`
      npm run dev
    env:
      DATABASE_URL: postgres://gitpod@localhost/regionscore

ports:
  - port: 5173
    onOpen: open-browser
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - svelte.svelte-vscode
    - Prisma.prisma

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true